/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void createRestaurant_draw1(PApplet appc, GWinData data) { //_CODE_:createNewRestaurant:739948:
  appc.background(230);
} //_CODE_:createNewRestaurant:739948:

public void RestaurantNameTextBox(GTextField source, GEvent event) { //_CODE_:RestaurantName:893966:
  restaurantName = RestaurantName.getText();
  RestaurantNameLabel.setText(restaurantName);
} //_CODE_:RestaurantName:893966:

public void RestaurantLocationPicked(GDropList source, GEvent event) { //_CODE_:RestaurantLocation:847766:
  location = RestaurantLocation.getSelectedText();
} //_CODE_:RestaurantLocation:847766:

public void CreateRestaurantClicked(GButton source, GEvent event) { //_CODE_:CreateRestaurant:252882:
  restaurantControls.setVisible(true);
  createNewRestaurant.setVisible(false);
  setGUIValues();
} //_CODE_:CreateRestaurant:252882:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:restaurantControls:326431:
  appc.background(230);
} //_CODE_:restaurantControls:326431:

public void NumberOfServersChanged(GCustomSlider source, GEvent event) { //_CODE_:NumberOfServers:708771:
  numOfServers = NumberOfServers.getValueF();
  createServers();
} //_CODE_:NumberOfServers:708771:

public void NumberOfChefsChanged(GCustomSlider source, GEvent event) { //_CODE_:NumberOfChefs:864665:
  numOfChefs = NumberOfChefs.getValueF();
  createChefs();
} //_CODE_:NumberOfChefs:864665:

public void ServerSkillSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:ServerSkillSlider:381628:
  serverSkill = ServerSkillSlider.getValueI();
} //_CODE_:ServerSkillSlider:381628:

public void ChefSkillSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:ChefSkillSlider:495450:
  chefSkill = ChefSkillSlider.getValueI();
} //_CODE_:ChefSkillSlider:495450:

public void CustomerRateSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:CustomerRateSlider:256650:
  customerRate = CustomerRateSlider.getValueF();
} //_CODE_:CustomerRateSlider:256650:

public void CostOfFoodSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:CostOfFoodSlider:407025:
  costOfFood = CostOfFoodSlider.getValueF();
} //_CODE_:CostOfFoodSlider:407025:

public void PauseButtonClicked(GButton source, GEvent event) { //_CODE_:PauseButton:921997:
  paused = !paused;
  setGUIValues();
  
  if (paused) {
    PauseButton.setText("Resume");
  }
  else {
    PauseButton.setText("Pause");
  }
} //_CODE_:PauseButton:921997:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  createNewRestaurant = GWindow.getWindow(this, "Create_Restaurant", 0, 0, 380, 285, JAVA2D);
  createNewRestaurant.noLoop();
  createNewRestaurant.setActionOnClose(G4P.KEEP_OPEN);
  createNewRestaurant.addDrawHandler(this, "createRestaurant_draw1");
  Heading = new GLabel(createNewRestaurant, 130, 10, 120, 20);
  Heading.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Heading.setText("Create Restaurant");
  Heading.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  Heading.setOpaque(false);
  restaurantNameLabel = new GLabel(createNewRestaurant, 10, 40, 110, 20);
  restaurantNameLabel.setText("Restaurant Name:");
  restaurantNameLabel.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  restaurantNameLabel.setOpaque(false);
  restaurantLocationLabel = new GLabel(createNewRestaurant, 10, 65, 120, 20);
  restaurantLocationLabel.setText("Restaurant Location:");
  restaurantLocationLabel.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  restaurantLocationLabel.setOpaque(false);
  label1 = new GLabel(createNewRestaurant, 10, 90, 100, 20);
  label1.setText("Location Options:");
  label1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  label1.setOpaque(false);
  torontoLabel = new GLabel(createNewRestaurant, 5, 120, 120, 20);
  torontoLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  torontoLabel.setText("Downtown Toronto");
  torontoLabel.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  torontoLabel.setOpaque(false);
  waterlooLabel = new GLabel(createNewRestaurant, 130, 120, 120, 20);
  waterlooLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  waterlooLabel.setText("Waterloo");
  waterlooLabel.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  waterlooLabel.setOpaque(false);
  eloraLabel = new GLabel(createNewRestaurant, 255, 120, 120, 20);
  eloraLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  eloraLabel.setText("Elora");
  eloraLabel.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  eloraLabel.setOpaque(false);
  RestaurantName = new GTextField(createNewRestaurant, 125, 40, 160, 20, G4P.SCROLLBARS_NONE);
  RestaurantName.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  RestaurantName.setOpaque(true);
  RestaurantName.addEventHandler(this, "RestaurantNameTextBox");
  RestaurantLocation = new GDropList(createNewRestaurant, 135, 64, 150, 80, 3, 10);
  RestaurantLocation.setItems(loadStrings("list_847766"), 0);
  RestaurantLocation.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  RestaurantLocation.addEventHandler(this, "RestaurantLocationPicked");
  TorontoDescription = new GLabel(createNewRestaurant, 5, 145, 120, 55);
  TorontoDescription.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  TorontoDescription.setText("A prime downtown Toronto location with high foot traffic and strong visibility.");
  TorontoDescription.setOpaque(false);
  TorontoRentLabel = new GLabel(createNewRestaurant, 5, 205, 120, 30);
  TorontoRentLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  TorontoRentLabel.setText("Rent Price: $5000/month");
  TorontoRentLabel.setOpaque(false);
  WaterlooDescriptionLabel = new GLabel(createNewRestaurant, 130, 145, 120, 55);
  WaterlooDescriptionLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  WaterlooDescriptionLabel.setText("A central Waterloo location, easily accessible with steady foor traffic.");
  WaterlooDescriptionLabel.setOpaque(false);
  WaterlooRentLabel = new GLabel(createNewRestaurant, 130, 205, 120, 30);
  WaterlooRentLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  WaterlooRentLabel.setText("Rent Price: $3000/month");
  WaterlooRentLabel.setOpaque(false);
  EloraRentLabel = new GLabel(createNewRestaurant, 255, 205, 120, 30);
  EloraRentLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  EloraRentLabel.setText("Rent Price: $2200/month");
  EloraRentLabel.setOpaque(false);
  EloraDescriptionLabel = new GLabel(createNewRestaurant, 255, 145, 120, 55);
  EloraDescriptionLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  EloraDescriptionLabel.setText("A charming Elora location in the heart of the town with a flow of friendly locals.");
  EloraDescriptionLabel.setOpaque(false);
  CreateRestaurant = new GButton(createNewRestaurant, 130, 245, 120, 30);
  CreateRestaurant.setText("Create Restaurant");
  CreateRestaurant.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  CreateRestaurant.addEventHandler(this, "CreateRestaurantClicked");
  restaurantControls = GWindow.getWindow(this, "Restaurant Controls", 0, 0, 240, 360, JAVA2D);
  restaurantControls.noLoop();
  restaurantControls.setActionOnClose(G4P.KEEP_OPEN);
  restaurantControls.addDrawHandler(this, "win_draw1");
  WelcomeSign = new GLabel(restaurantControls, 80, 10, 80, 20);
  WelcomeSign.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  WelcomeSign.setText("Welcome to");
  WelcomeSign.setOpaque(false);
  RestaurantNameLabel = new GLabel(restaurantControls, 45, 30, 150, 20);
  RestaurantNameLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  RestaurantNameLabel.setText("Restaurant Name");
  RestaurantNameLabel.setOpaque(false);
  AmountOfServers = new GLabel(restaurantControls, 20, 65, 80, 20);
  AmountOfServers.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  AmountOfServers.setText("# of Servers");
  AmountOfServers.setOpaque(false);
  AmountOfChefs = new GLabel(restaurantControls, 140, 65, 80, 20);
  AmountOfChefs.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  AmountOfChefs.setText("# of Chefs");
  AmountOfChefs.setOpaque(false);
  NumberOfServers = new GCustomSlider(restaurantControls, 10, 90, 100, 45, "grey_blue");
  NumberOfServers.setShowValue(true);
  NumberOfServers.setLimits(4, 1, 10);
  NumberOfServers.setNbrTicks(10);
  NumberOfServers.setStickToTicks(true);
  NumberOfServers.setShowTicks(true);
  NumberOfServers.setNumberFormat(G4P.INTEGER, 0);
  NumberOfServers.setOpaque(false);
  NumberOfServers.addEventHandler(this, "NumberOfServersChanged");
  NumberOfChefs = new GCustomSlider(restaurantControls, 130, 90, 100, 45, "grey_blue");
  NumberOfChefs.setShowValue(true);
  NumberOfChefs.setLimits(1, 1, 10);
  NumberOfChefs.setNbrTicks(10);
  NumberOfChefs.setStickToTicks(true);
  NumberOfChefs.setShowTicks(true);
  NumberOfChefs.setNumberFormat(G4P.INTEGER, 0);
  NumberOfChefs.setOpaque(false);
  NumberOfChefs.addEventHandler(this, "NumberOfChefsChanged");
  ServerSkillSlider = new GCustomSlider(restaurantControls, 10, 170, 100, 45, "grey_blue");
  ServerSkillSlider.setShowValue(true);
  ServerSkillSlider.setLimits(5, 1, 10);
  ServerSkillSlider.setNbrTicks(10);
  ServerSkillSlider.setStickToTicks(true);
  ServerSkillSlider.setShowTicks(true);
  ServerSkillSlider.setNumberFormat(G4P.INTEGER, 0);
  ServerSkillSlider.setOpaque(false);
  ServerSkillSlider.addEventHandler(this, "ServerSkillSliderChanged");
  ChefSkillSlider = new GCustomSlider(restaurantControls, 130, 170, 100, 45, "grey_blue");
  ChefSkillSlider.setShowValue(true);
  ChefSkillSlider.setLimits(5, 1, 10);
  ChefSkillSlider.setNbrTicks(10);
  ChefSkillSlider.setStickToTicks(true);
  ChefSkillSlider.setShowTicks(true);
  ChefSkillSlider.setNumberFormat(G4P.INTEGER, 0);
  ChefSkillSlider.setOpaque(false);
  ChefSkillSlider.addEventHandler(this, "ChefSkillSliderChanged");
  ServerSkillLabel = new GLabel(restaurantControls, 20, 145, 80, 20);
  ServerSkillLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  ServerSkillLabel.setText("Server Skill");
  ServerSkillLabel.setOpaque(false);
  ChefSkillLabel = new GLabel(restaurantControls, 140, 145, 80, 20);
  ChefSkillLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  ChefSkillLabel.setText("Chef Skill");
  ChefSkillLabel.setOpaque(false);
  CustomerRateLabel = new GLabel(restaurantControls, 15, 225, 90, 20);
  CustomerRateLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  CustomerRateLabel.setText("Customer Rate");
  CustomerRateLabel.setOpaque(false);
  CostOfFoodLabel = new GLabel(restaurantControls, 140, 225, 80, 20);
  CostOfFoodLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  CostOfFoodLabel.setText("Cost of Food");
  CostOfFoodLabel.setOpaque(false);
  CustomerRateSlider = new GCustomSlider(restaurantControls, 10, 250, 100, 45, "grey_blue");
  CustomerRateSlider.setShowValue(true);
  CustomerRateSlider.setLimits(2, 1, 10);
  CustomerRateSlider.setNbrTicks(10);
  CustomerRateSlider.setStickToTicks(true);
  CustomerRateSlider.setShowTicks(true);
  CustomerRateSlider.setNumberFormat(G4P.INTEGER, 0);
  CustomerRateSlider.setOpaque(false);
  CustomerRateSlider.addEventHandler(this, "CustomerRateSliderChanged");
  CostOfFoodSlider = new GCustomSlider(restaurantControls, 130, 250, 100, 45, "DECIMAL");
  CostOfFoodSlider.setShowValue(true);
  CostOfFoodSlider.setLimits(20, 10, 40);
  CostOfFoodSlider.setNbrTicks(7);
  CostOfFoodSlider.setStickToTicks(true);
  CostOfFoodSlider.setShowTicks(true);
  CostOfFoodSlider.setNumberFormat(G4P.INTEGER, 0);
  CostOfFoodSlider.setOpaque(false);
  CostOfFoodSlider.addEventHandler(this, "CostOfFoodSliderChanged");
  PauseButton = new GButton(restaurantControls, 80, 310, 80, 30);
  PauseButton.setText("Resume");
  PauseButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  PauseButton.addEventHandler(this, "PauseButtonClicked");
  createNewRestaurant.loop();
  restaurantControls.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow createNewRestaurant;
GLabel Heading; 
GLabel restaurantNameLabel; 
GLabel restaurantLocationLabel; 
GLabel label1; 
GLabel torontoLabel; 
GLabel waterlooLabel; 
GLabel eloraLabel; 
GTextField RestaurantName; 
GDropList RestaurantLocation; 
GLabel TorontoDescription; 
GLabel TorontoRentLabel; 
GLabel WaterlooDescriptionLabel; 
GLabel WaterlooRentLabel; 
GLabel EloraRentLabel; 
GLabel EloraDescriptionLabel; 
GButton CreateRestaurant; 
GWindow restaurantControls;
GLabel WelcomeSign; 
GLabel RestaurantNameLabel; 
GLabel AmountOfServers; 
GLabel AmountOfChefs; 
GCustomSlider NumberOfServers; 
GCustomSlider NumberOfChefs; 
GCustomSlider ServerSkillSlider; 
GCustomSlider ChefSkillSlider; 
GLabel ServerSkillLabel; 
GLabel ChefSkillLabel; 
GLabel CustomerRateLabel; 
GLabel CostOfFoodLabel; 
GCustomSlider CustomerRateSlider; 
GCustomSlider CostOfFoodSlider; 
GButton PauseButton; 
